### Create new Report
POST http://localhost:3001/reports
Content-Type: application/json

{
  "title" : "New Report Home test Backend",
  "description": "Eu enim ipsum sint qui anim.",
  "price": 540,
  "content": "Ea commodo nulla enim commodo."
}


### Get All Reports
GET http://localhost:3001/reports


### Update Report
PATCH http://localhost:3001/reports/63a9a38e7aefddb545763ec0
Content-Type: application/json

{
  "title": "Update Report",
  "content": "Est ut sunt quis id cillum nostrud deserunt cupidatat dolor.",
  "price": 250
}


### Find One Report By Id
GET http://localhost:3001/reports/63a9a38e7aefddb545763ec0

### Remove Report
DELETE http://localhost:3001/reports/63a9a38e7aefddb545763ec0