### Create new Report
POST http://localhost:3001/reports
Content-Type: application/json

{
  "title" : "New Report Home",
  "description": "Consectetur exercitation eiusmod id laboris voluptate voluptate tempor exercitation nisi et.",
  "price": 230,
  "content": "Pariatur qui aliqua deserunt aliqua anim."
}


### Get All Reports
GET http://localhost:3001/reports


### Update Report
PATCH http://localhost:3001/reports/63a9a38e7aefddb545763ec0
Content-Type: application/json

{
  "title": "Update Report",
  "content": "Est ut sunt quis id cillum nostrud deserunt cupidatat dolor.",
  "price": 250
}


### Find One Report By Id
GET http://localhost:3001/reports/63a9a38e7aefddb545763ec0

### Remove Report
DELETE http://localhost:3001/reports/63a9a38e7aefddb545763ec0